/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/docs/[lang]/': RouteRecordInfo<'/docs/[lang]/', '/docs/:lang', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/docs/[lang]/[...pathMatch]': RouteRecordInfo<'/docs/[lang]/[...pathMatch]', '/docs/:lang/:pathMatch(.*)', { lang: ParamValue<true>, pathMatch: ParamValue<true> }, { lang: ParamValue<false>, pathMatch: ParamValue<false> }>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/profile/': RouteRecordInfo<'/users/profile/', '/users/profile', Record<never, never>, Record<never, never>>,
  }
}
